// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLt-FlOxlcPVUXa12pK-IA3dq4Dgr_uRU',
    appId: '1:428716148000:web:8f02e50f34213328058345',
    messagingSenderId: '428716148000',
    projectId: 'lab-test-73a6e',
    authDomain: 'lab-test-73a6e.firebaseapp.com',
    storageBucket: 'lab-test-73a6e.appspot.com',
    measurementId: 'G-2NK0KN9SJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChy80Xdzqq60IlIHjT9XbsdJsJ9XmXtw0',
    appId: '1:428716148000:android:6e74443378e6be2e058345',
    messagingSenderId: '428716148000',
    projectId: 'lab-test-73a6e',
    storageBucket: 'lab-test-73a6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG6fxfQw_4MMRugT3mKhttp-atTIGYrk0',
    appId: '1:428716148000:ios:ccb378cca37584a3058345',
    messagingSenderId: '428716148000',
    projectId: 'lab-test-73a6e',
    storageBucket: 'lab-test-73a6e.appspot.com',
    iosClientId: '428716148000-auqbuvrcmhu9r3qn0ulamjgghglq14fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG6fxfQw_4MMRugT3mKhttp-atTIGYrk0',
    appId: '1:428716148000:ios:ccb378cca37584a3058345',
    messagingSenderId: '428716148000',
    projectId: 'lab-test-73a6e',
    storageBucket: 'lab-test-73a6e.appspot.com',
    iosClientId: '428716148000-auqbuvrcmhu9r3qn0ulamjgghglq14fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.labTest',
  );
}
